# Generated by Django 6.0.5 on 2026-05-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
