# Generated by Django 6.0.5 on 2026-05-17 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('stall_type', models.CharField(choices=[('food', 'Food'), ('fashion', 'Fashion'), ('business', 'Business'), ('arts', 'Arts'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('doc_lambeth_questionnaire', models.BooleanField(default=False, verbose_name='Lambeth Food H&S Questionnaire')),
                ('doc_public_liability', models.BooleanField(default=False, verbose_name='Public Liability Insurance')),
                ('doc_hygiene_certificate', models.BooleanField(default=False, verbose_name='Food Hygiene Training Certificate')),
                ('doc_menu', models.BooleanField(default=False, verbose_name='Menu / Description')),
                ('doc_gas_safety', models.BooleanField(default=False, verbose_name='Gas Safety Certificate')),
                ('doc_allergen_matrix', models.BooleanField(default=False, verbose_name='Allergen Matrix')),
                ('halal_certified', models.BooleanField(default=False, verbose_name='Halal Certified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('documents_requested', 'Documents Requested'), ('documents_complete', 'Documents Complete'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('stall_location', models.CharField(blank=True, max_length=100)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_applications', to='core.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
