# Generated by Django 6.0.5 on 2026-05-17 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('tier_interest', models.CharField(choices=[('event_partner', 'Event Partner'), ('strategic_partner', 'Strategic Partner'), ('community_partner', 'Community Partner'), ('supporter', 'Supporter'), ('friend', 'Friend'), ('undecided', 'Undecided')], default='undecided', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_discussion', 'In Discussion'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('lost', 'Lost')], default='new', max_length=20)),
                ('confirmed_tier', models.CharField(blank=True, max_length=30)),
                ('confirmed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_leads', to='core.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
