# Generated by Django 6.0.5 on 2026-05-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlead',
            name='tier_interest',
            field=models.CharField(choices=[('title_sponsor', 'Title Sponsor (from £10,000)'), ('diamond', 'Diamond (from £5,000)'), ('platinum', 'Platinum (from £3,000)'), ('gold', 'Gold (£2,000)'), ('silver', 'Silver (£1,000)'), ('undecided', 'Not sure yet')], default='undecided', max_length=30),
        ),
    ]
